# 行列積の実装

### パラメータ

In [1]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

## 【問題1】行列積を手計算する

$$A = \begin{bmatrix}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9 \\
\end{bmatrix}
,B = 
\begin{bmatrix}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1 \\
\end{bmatrix}  
$$

$$
AB = \begin{bmatrix}
(-1*0)+(2*0)+(3*2) & (-1*2)+(2*2)+(3*9) & (-1*1)+(2*-8)+(3*-1) \\
(4*0)+(-5*0)+(6*2) & (4*2)+(-5*2)+(6*9) & (4*1)+(-5*-8)+(6*-1) \\
(7*0)+(8*0)+(-9*2) & (7*2)+(8*2)+(-9*9) & (7*1)+(8*-8)+(-9*-1) \\
\end{bmatrix}
$$

$$AB = \begin{bmatrix}
6 & 29 & -20 \\
12 & 52 & 38 \\
-18 & -51 & -48 \\
\end{bmatrix}
$$

## 【問題2】NumPyの関数による計算

In [2]:
# a_ndarrayとb_ndarrayの行列積を求める
print(np.matmul(a_ndarray, b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 【問題3】ある要素の計算を実装
$$\sum_{k=0}^{2}a_{0,k},b_{k,0}$$

In [3]:
count = 0

for i in range(3):
	count += a_ndarray[0][i] * b_ndarray[i][0]

print(count)

6


## 【問題4】行列積を行う関数の作成

In [4]:
# 関数の宣言
def matrix_product_calculator(matrix_1, matrix_2):
	"""
	function : 行列1[matrix_1]と行列2[matrix_2]の行列積[matrix_product]を返す関数

	:param matrix_1: array
		行列1
	:param matrix_2: array
		行列2

	count : int (計算用)
		計算結果格納用
	list_of_matrix_12 : list (格納用)
		計算結果を配列に変える前に保存しておくリスト

	:return: matrix_product: array
		行列1と行列2の行列積
	"""

	# 初期値の設定
	count = 0
	list_of_matrix_12 = []
	# 計算
	for i in range(matrix_1.shape[0]):
		for j in range(matrix_2.shape[1]):
			# ここのrangeはmatrix_2.shape[0]でも可能(同じ値をとる)
			for k in range(matrix_1.shape[1]):
				count += matrix_1[i][k] * matrix_2[k][j]
			# 結果の保存
			list_of_matrix_12.append(count)
			# 値のリセット
			count = 0

	# リストをarrayに変換、積の形にreshape
	matrix_product = np.array(list_of_matrix_12).reshape(matrix_1.shape[0], matrix_2.shape[1])
	# 返り値の設定
	return matrix_product

In [5]:
# 結果の格納および表示
c_ndarray = matrix_product_calculator(a_ndarray, b_ndarray)
print(c_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 【問題5】計算が定義されない入力を判定する
###  パラメータの追加

In [6]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [7]:
# d_ndarrayとe_ndarrayで行列積を求めようとすると行列dの列数と行列eの行数が異なるため、エラー
matrix_product_calculator(d_ndarray, e_ndarray)

IndexError: index 2 is out of bounds for axis 0 with size 2

In [8]:
# 改訂版関数の宣言
def matrix_product_calculator_revised(matrix_1, matrix_2):
	"""
	function : 行列1[matrix_1]と行列2[matrix_2]の行列積[matrix_product]を返す関数

	:param matrix_1: array
		行列1
	:param matrix_2: array
		行列2

	count : int (計算用)
		計算結果格納用
	list_of_matrix_12 : list (格納用)
		計算結果を配列に変える前に保存しておくリスト

	:return: matrix_product: array
		行列1と行列2の行列積
	"""

	# 計算可能か判断
	if matrix_1.shape[1] != matrix_2.shape[0]:
		print('行列1の列数と行列2の行数が異なるため、計算できません。')
	else:
		# 初期値の設定
		count = 0
		list_of_matrix_12 = []
		# 計算
		for i in range(matrix_1.shape[0]):
			for j in range(matrix_2.shape[1]):
				# ここのrangeはmatrix_2.shape[0]でも可能(同じ値をとる)
				for k in range(matrix_1.shape[1]):
					count += matrix_1[i][k] * matrix_2[k][j]
				# 結果の保存
				list_of_matrix_12.append(count)
				# 値のリセット
				count = 0

		# リストをarrayに変換、積の形にreshape
		matrix_product = np.array(list_of_matrix_12).reshape(matrix_1.shape[0], matrix_2.shape[1])
		# 返り値の設定
		return matrix_product


In [10]:
# 結果の格納及び表示
matrix_product_calculator_revised(d_ndarray, e_ndarray)

行列1の列数と行列2の行数が異なるため、計算できません。


## 【問題6】転置

In [11]:
# e_ndarrayの置換行列を求める
e_ndarray_transpose = np.transpose(e_ndarray)
print(e_ndarray_transpose.shape)

(3, 2)


In [12]:
# d_ndarrayとe_ndarrayの置換行列の行列積を求める
de_transpose = matrix_product_calculator_revised(d_ndarray, e_ndarray_transpose)
print(de_transpose)

[[ 46  -4]
 [-34  73]]


In [13]:
# 結果が正しいのか確認
print(np.matmul(d_ndarray, e_ndarray_transpose) == de_transpose)

[[ True  True]
 [ True  True]]
